/**
 * Seed data for Space Repetition Tutor
 *
 * This app is language-agnostic and starts with no pre-populated data.
 * Topics and questions are created by users or generated by the LLM.
 *
 * This file is kept for compatibility but does nothing.
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('No seed data to create. The app starts clean.');
  console.log('Topics and questions are created by users or the LLM.');
}

main()
  .catch((e) => {
    console.error('Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
